- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        var: ansible_facts
    - name: Create SSH
      environment:
        PATH: "/usr/bin:{{ ansible_env.PATH }}"
      openssh_keypair:
        path: '/tmp/id_ssh_rsa'
      register: ssh_key_local
    
