- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Create SSH
      openssh_keypair:
        path: '/tmp/id_ssh_rsa'
        register: ssh_key_local
    
