- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        var: ansible_facts
    - name: Create SSH
      connection: local
      openssh_keypair:
        path: '/tmp/id_ssh_rsa'
      register: ssh_key_local
    
