- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Check if binary exists in PATH
      command: which ssh-keygen
      ignore_errors: true
      register: which_out 
    - name: Hello
      debug:
        msg: "{{ my_var }}"
    - name: Create SSH
      openssh_keypair:
        path: '/tmp/id_ssh_rsa'
      register: ssh_key_local
    - name: Install ansible-pylibssh
      pip:
        name: ansible-pylibssh
        state: present
    - name: Display the path of ansible-pylibssh library
      command: "pip show ansible-pylibssh | grep 'Location:' | awk '{print $2}'"
      register: ansible_pylibssh_path

    - name: Debug ansible-pylibssh path
      ansible.builtin.debug:
        var: ansible_pylibssh_path.stdout

    - name: "gateways"  
      hosts: vyos  
      gather_facts: no 
      
    - name: Gather facts (vyos)  
      vyos.vyos.vyos_facts:  
      when: ansible_network_os == 'vyos.vyos.vyos'  

    # Demonstrate variables  
    - name: Display some facts  
      debug:  
      msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"  

    - name: Facts from a specific host  
      debug:  
      var: hostvars[ansible_net_hostname]</div>

    
