- name: Test ansible-pylibssh package installation 
  hosts: localhost
  tasks:
    - name: Install ansible-pylibssh
      pip:
        name: ansible-pylibssh
        state: present
    - name: Display the path of ansible-pylibssh library
      command: "pip show ansible-pylibssh | grep 'Location:' | awk '{print $2}'"
      register: ansible_pylibssh_path

    - name: Debug ansible-pylibssh path
      ansible.builtin.debug:
        var: ansible_pylibssh_path.stdout

    
