---
collections:
  - name: https://github.ibm.com/amallak1/test-collection.git
    type: git
    version: v1.0.0
- name: Print IP Address of Host
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print IP Address
      debug:
        msg: "IP Address of {{ inventory_hostname }} is {{ ansible_default_ipv4.address }}"
